apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-mgmt-saml-auth-lightblue-applications-fou3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-mgmt-saml-auth-lightblue-applications-fou3
    app.kubernetes.io/part-of: dhaynes-lightblue-applications
  name: data-mgmt-saml-auth-lightblue-applications-fou3
  namespace: dhaynes-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: data-mgmt-saml-auth-lightblue-applications-fou3
    weight: null
status: {}
